import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextAuthProvider from "@/contexts/NextAuthProvider";
import { ReactQueryClientProvider } from "@/components/QueryClientProvider";
import { Toaster } from "@/components/ui/sonner";
import { ApplicationProvider } from "@/contexts/application/application.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body className={"h-screen bg-[#F6F9F6]" + inter.className}>
        <NextAuthProvider>
          <ReactQueryClientProvider>
            <ApplicationProvider>{children}</ApplicationProvider>
            <Toaster richColors position="top-right" theme="light" />
          </ReactQueryClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
