import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextAuthProvider from "@/contexts/NextAuthProvider";
import { ReactQueryClientProvider } from "@/components/QueryClientProvider";
import SideNavBar from "./_components/SideNavBar";
import { Toaster } from "@/components/ui/sonner";
import { MqttConnect } from "./_components/MqttConnect";
import { ApplicationProvider } from "@/contexts/application/application.context";
// import ApplicationWrapper from "@/components/core/ApplicationWrapper";
import { Suspense } from "react";
// import Alerts from "./_components/Alerts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body className={"h-screen overflow-hidden " + inter.className}>
        <div className="h-screen flex flex-col">
          <NextAuthProvider>
            <ApplicationProvider>
              <ReactQueryClientProvider>
                <MqttConnect>
                  <Suspense>
                    {/* <ApplicationWrapper> */}
                    <div className="min-h-0 flex-1 flex overflow-hidden">
                      <SideNavBar />
                      <main className="min-w-0 flex-1 flex flex-col bg-[#eef1ee]">
                        {/* <Alerts /> */}
                        <div className="flex-1 overflow-auto">{children}</div>
                      </main>
                    </div>
                    {/* </ApplicationWrapper> */}
                  </Suspense>
                  <Toaster richColors position="top-right" theme="light" />
                </MqttConnect>
              </ReactQueryClientProvider>
            </ApplicationProvider>
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
