import { Alert } from "@/components/ui/alert";

export const BRANCH_ID = "6629e1a67bfcd68cff08a29e";

export const API_ENDPOINTS = {
  TEMPLATE: "/template",
  LIBRARY: "/library",
  FLOW: "/flow",
  WORK_FLOW: "/work-flow",
  INDUSTRIES: "/industries",
  INTEGRATIONS: "/integration",
  CATEGORY: "/category",
  USECASE: "/use-case",
  MEDIA: "/media",
  UPLOAD: "/upload",
  BUSINESS: "/business",
  USERACCOUNT: "/user-account",
  USERS: "/users",
  PAYMENT: "/payment",
  SETTINGS: "/settings",
  SUBSCRIPTION: "/subscription",
  IAM: "/iam",
  POLICIES: "/policies",
  WEBHOOK: "/webhook-subscription",
  PRODUCT: "/product",
  ALERT_MESSAGE: "/alert-message",
  DASHBOARD: "/dashboard",
  OVERVIEW: "/overview",
  RECENT: "/recent",
  USER_LOGIN: "/user-login-activity",
  ONBOARDING_USER: "/onboarding-user",
  WORKSPACE: "/workspace",
  PARTNER: "/partner",
  CATALOG: "/catalog",
  ADDON: "/addon",
  WORKSPACE_ADDON: "/workspace-addon",
  WHATSAPP:"/whatsapp",
  INSTAGRAM:"/instagram",
  MODULES:"/modules",
};
