export const timezones = [
  {
    name: "Pacific/Midway",
    code: "SST",
    display_name: "Midway Island",
    display_with_offset: "(-11:00) Midway Island",
    offset: -11,
  },
  {
    name: "Pacific/Honolulu",
    code: "HST",
    display_name: "Hawaii",
    display_with_offset: "(-10:00) Hawaii",
    offset: -10,
  },
  {
    name: "America/Anchorage",
    code: "AKDT",
    display_name: "Anchorage",
    display_with_offset: "(-08:00) Anchorage",
    offset: -8,
  },
  {
    name: "America/Juneau",
    code: "AKDT",
    display_name: "Alaska",
    display_with_offset: "(-08:00) Alaska",
    offset: -8,
  },
  {
    name: "America/Los_Angeles",
    code: "PDT",
    display_name: "Pacific Time (US & Canada)",
    display_with_offset: "(-07:00) Pacific Time (US & Canada)",
    offset: -7,
  },
  {
    name: "America/Tijuana",
    code: "PDT",
    display_name: "Tijuana",
    display_with_offset: "(-07:00) Tijuana",
    offset: -7,
  },
  {
    name: "America/Phoenix",
    code: "MST",
    display_name: "Arizona",
    display_with_offset: "(-07:00) Arizona",
    offset: -7,
  },
  {
    name: "America/Denver",
    code: "MDT",
    display_name: "Mountain Time (US & Canada)",
    display_with_offset: "(-06:00) Mountain Time (US & Canada)",
    offset: -6,
  },
  {
    name: "America/Chicago",
    code: "CDT",
    display_name: "Central Time (US & Canada)",
    display_with_offset: "(-05:00) Central Time (US & Canada)",
    offset: -5,
  },
  {
    name: "America/Mexico_City",
    code: "CDT",
    display_name: "Mexico City",
    display_with_offset: "(-05:00) Mexico City",
    offset: -5,
  },
  {
    name: "America/New_York",
    code: "EDT",
    display_name: "Eastern Time (US & Canada)",
    display_with_offset: "(-04:00) Eastern Time (US & Canada)",
    offset: -4,
  },
  {
    name: "America/Halifax",
    code: "ADT",
    display_name: "Atlantic Time (Canada)",
    display_with_offset: "(-03:00) Atlantic Time (Canada)",
    offset: -3,
  },
  {
    name: "America/St_Johns",
    code: "NDT",
    display_name: "Newfoundland",
    display_with_offset: "(-02:30) Newfoundland",
    offset: -2.5,
  },
  {
    name: "America/Sao_Paulo",
    code: "BRT",
    display_name: "Brasilia",
    display_with_offset: "(-03:00) Brasilia",
    offset: -3,
  },
  {
    name: "Atlantic/South_Georgia",
    code: "GST",
    display_name: "Mid-Atlantic",
    display_with_offset: "(-02:00) Mid-Atlantic",
    offset: -2,
  },
  {
    name: "Atlantic/Cape_Verde",
    code: "CVT",
    display_name: "Cape Verde Is.",
    display_with_offset: "(-01:00) Cape Verde Is.",
    offset: -1,
  },
  {
    name: "Etc/UTC",
    code: "UTC",
    display_name: "UTC",
    display_with_offset: "(+00:00) UTC",
    offset: 0,
  },
  {
    name: "Europe/London",
    code: "BST",
    display_name: "London",
    display_with_offset: "(+01:00) London",
    offset: 1,
  },
  {
    name: "Europe/Paris",
    code: "CEST",
    display_name: "Paris",
    display_with_offset: "(+02:00) Paris",
    offset: 2,
  },
  {
    name: "Europe/Berlin",
    code: "CEST",
    display_name: "Berlin",
    display_with_offset: "(+02:00) Berlin",
    offset: 2,
  },
  {
    name: "Europe/Athens",
    code: "EEST",
    display_name: "Athens",
    display_with_offset: "(+03:00) Athens",
    offset: 3,
  },
  {
    name: "Europe/Istanbul",
    code: "TRT",
    display_name: "Istanbul",
    display_with_offset: "(+03:00) Istanbul",
    offset: 3,
  },
  {
    name: "Europe/Moscow",
    code: "MSK",
    display_name: "Moscow",
    display_with_offset: "(+03:00) Moscow",
    offset: 3,
  },
  {
    name: "Asia/Dubai",
    code: "GST",
    display_name: "Dubai",
    display_with_offset: "(+04:00) Dubai",
    offset: 4,
  },
  {
    name: "Asia/Baku",
    code: "AZT",
    display_name: "Baku",
    display_with_offset: "(+04:00) Baku",
    offset: 4,
  },
  {
    name: "Asia/Kabul",
    code: "AFT",
    display_name: "Kabul",
    display_with_offset: "(+04:30) Kabul",
    offset: 4.5,
  },
  {
    name: "Asia/Tehran",
    code: "IRDT",
    display_name: "Tehran",
    display_with_offset: "(+04:30) Tehran",
    offset: 4.5,
  },
  {
    name: "Asia/Tashkent",
    code: "UZT",
    display_name: "Tashkent",
    display_with_offset: "(+05:00) Tashkent",
    offset: 5,
  },
  {
    name: "Asia/Karachi",
    code: "PKT",
    display_name: "Karachi",
    display_with_offset: "(+05:00) Karachi",
    offset: 5,
  },
  {
    name: "Asia/Kolkata",
    code: "IST",
    display_name: "Kolkata",
    display_with_offset: "(+05:30) Kolkata",
    offset: 5.5,
  },
  {
    name: "Asia/Kathmandu",
    code: "NPT",
    display_name: "Kathmandu",
    display_with_offset: "(+05:45) Kathmandu",
    offset: 5.75,
  },
  {
    name: "Asia/Dhaka",
    code: "BDT",
    display_name: "Dhaka",
    display_with_offset: "(+06:00) Dhaka",
    offset: 6,
  },
  {
    name: "Asia/Almaty",
    code: "ALMT",
    display_name: "Almaty",
    display_with_offset: "(+06:00) Almaty",
    offset: 6,
  },
  {
    name: "Asia/Rangoon",
    code: "MMT",
    display_name: "Rangoon",
    display_with_offset: "(+06:30) Rangoon",
    offset: 6.5,
  },
  {
    name: "Asia/Bangkok",
    code: "ICT",
    display_name: "Bangkok",
    display_with_offset: "(+07:00) Bangkok",
    offset: 7,
  },
  {
    name: "Asia/Jakarta",
    code: "WIB",
    display_name: "Jakarta",
    display_with_offset: "(+07:00) Jakarta",
    offset: 7,
  },
  {
    name: "Asia/Shanghai",
    code: "CST",
    display_name: "Beijing",
    display_with_offset: "(+08:00) Beijing",
    offset: 8,
  },
  {
    name: "Asia/Singapore",
    code: "SGT",
    display_name: "Singapore",
    display_with_offset: "(+08:00) Singapore",
    offset: 8,
  },
  {
    name: "Asia/Seoul",
    code: "KST",
    display_name: "Seoul",
    display_with_offset: "(+09:00) Seoul",
    offset: 9,
  },
  {
    name: "Asia/Tokyo",
    code: "JST",
    display_name: "Tokyo",
    display_with_offset: "(+09:00) Tokyo",
    offset: 9,
  },
  {
    name: "Australia/Darwin",
    code: "ACST",
    display_name: "Darwin",
    display_with_offset: "(+09:30) Darwin",
    offset: 9.5,
  },
  {
    name: "Australia/Adelaide",
    code: "ACST",
    display_name: "Adelaide",
    display_with_offset: "(+09:30) Adelaide",
    offset: 9.5,
  },
  {
    name: "Australia/Sydney",
    code: "AEST",
    display_name: "Sydney",
    display_with_offset: "(+10:00) Sydney",
    offset: 10,
  },
  {
    name: "Australia/Brisbane",
    code: "AEST",
    display_name: "Brisbane",
    display_with_offset: "(+10:00) Brisbane",
    offset: 10,
  },
  {
    name: "Pacific/Guadalcanal",
    code: "SBT",
    display_name: "Solomon Is.",
    display_with_offset: "(+11:00) Solomon Is.",
    offset: 11,
  },
  {
    name: "Pacific/Auckland",
    code: "NZST",
    display_name: "Auckland",
    display_with_offset: "(+12:00) Auckland",
    offset: 12,
  },
  {
    name: "Pacific/Fiji",
    code: "FJT",
    display_name: "Fiji",
    display_with_offset: "(+12:00) Fiji",
    offset: 12,
  },
  {
    name: "Pacific/Tongatapu",
    code: "TOT",
    display_name: "Nuku'alofa",
    display_with_offset: "(+13:00) Nuku'alofa",
    offset: 13,
  },
];
