import { ReactQueryClientProvider } from "@/components/QueryClientProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kwic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body className={"h-screen" + inter.className}>
        <ReactQueryClientProvider>
          {children}
          <Toaster richColors position="top-right" theme="light" />
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
